# utils/state_definitions.py

AWAITING_STEP_2_SCAN_RESULTS = "AWAITING_STEP_2_SCAN_RESULTS"
AWAITING_STEP_2_ACK = "AWAITING_STEP_2_ACK"
AWAITING_STEP_3_CONFIRMATION = "AWAITING_STEP_3_CONFIRMATION"
AWAITING_STEP_4_DECISION = "AWAITING_STEP_4_DECISION"
AWAITING_FINAL_PAYMENT = "AWAITING_FINAL_PAYMENT"
